- hosts: all
  sudo: True
  vars:
    db_sentry:
      name: sentry
      user: sentry
      password: sentrysentry
    superuser_sentry:
      username: admin
      email: admin@example.com
      password: admin
    sentry:
      server: sentry.todaytix.com
      url: https://sentry.todaytix.com      
  roles:
    - common
    - python
    - supervisor
    - role: nginx
      nginx_sites: none 
    - postgres
    - sentry

